### ISSUE TITLE
crash on existing server start with armor

### ISSUE THREAD

**Issue by aldo1028** [TFC-Metallum/TFC-Metallum#13]
issue with Metallum on server load event on an existing server with the following crash report
[crash-2019-09-23_19.36.32-client.txt](https://github.com/TFC-Metallum/TFC-Metallum/files/3644562/crash-2019-09-23_19.36.32-client.txt)

**Comment by DisasterMoo** [comment]
Looks like it is fixed by TFC dependency update.
