### ISSUE TITLE
Poorly registration of ore dictionary by TFC

### ISSUE THREAD

**Issue by Mrthomas20121** [TFC-Metallum/TFC-Metallum#23]
Rich, normal and poor cobaltite have the oredict oreCobaltRich/normal/poor
while the small cobaltite have the following oredict 
![image](https://user-images.githubusercontent.com/34064092/69117432-ecf06500-0a8f-11ea-8e61-cdb5a43a312d.png)
 Something is obviously wrong.

**Comment by DisasterMoo** [comment]
Looks like that's a bug in TFC actually. TFC register it's small ores by the name of the ore and the rich/normal/poor by the name of the metal. Look at Hematite / Limonite / Magnetite or Native Copper / Tetrahedrite for example.

**Comment by DisasterMoo** [comment]
Fixed by TFC build 96+
