### ISSUE TITLE
Metals not smelting in the pit kiln. 

### ISSUE THREAD

**Issue by V4m4cher0n** [TFC-Metallum/TFC-Metallum#26]
For some reason when I smelt certain metals from this mod in a pit kiln, they just disappear instead of turning into liquid within the vessel. I've tested this with ardite, cobaltite and a few more metals in the mod.

**Comment by Abdyman** [comment]
how exactly are you going about this, what item are you using? are you using ores, or are you using items like ingots/dust or something else.

**Comment by DisasterMoo** [comment]
That's because cobaltite and ardite are Tier IV and Tier VI respectively. The pit kiln can only melt ores from Tier I and alloys it further to Tier II.

But I do know what is the problem here: The pit kiln should not void items but instead not melt them. It's a bug in base TFC.

**Comment by DisasterMoo** [comment]
TFC now melts any unmeltable ores into unknown alloy instead of just voiding.
