### ISSUE TITLE
New Metals

### ISSUE THREAD

**Issue by DisasterMoo** [TFC-Metallum/TFC-Metallum#30]
Taken from the suggestion issue (see #21)

- [x] Red Alloy (Redstone + Copper)
- [x] Nickel Brass / Nickel Silver (Copper + Nickel + Zinc)

Not adding conditional registration since that cause more issues than resolve. (Sorry, no magic metals since the mod whose add those normally register tools, not needing me to duplicate it)

**Comment by UnlimatedStone9** [comment]
Might I add a few new metals suggested by a user on the CurseForge page?
-Magnesium
-Lithium
-Boron
-Thorium
-Uranium

**Comment by DisasterMoo** [comment]
> Might I suggest a few new metals suggested by a user on the CurseForge page?
> -Magnesium
> -Lithium
> -Boron
> -Thorium
> -Uranium

Not sure about metals, but imo ores should be added for compatibility. If ore dict can't help with the crushing / smelting or w/e recipe, there's always CT to fill the gap.

**Comment by Mrthomas20121** [comment]
Boron is already added as a gem in tfc. the others could be added as ores like you mentionned.

**Comment by DisasterMoo** [comment]
If anyone is wondering:
- Magnesium = Should be processed from magnesite (was already part of Metallum prior to v1.1.3)
- Lithium = Added Spodumene in v1.1.3
- Boron = Was already in Metallum prior to v1.1.3, i just buffed up their spawn rate
- Thorium = Should be processed from thorianite (was already part of Metallum prior to v1.1.3)
- Uranium = Should be processed from pitchblende, part of TFC itself.
