### ISSUE TITLE
certain ores dont have a smelting into liquid or ingot recipe

### ISSUE THREAD

**Issue by TheNimbleNinja** [TFC-Metallum/TFC-Metallum#32]
ive found that cobalt tungsten and aluminum dont have smelting into liquid or turning into an ingot recipes and i need them for my pack :(

**Comment by DisasterMoo** [comment]
That's intended. The ores you suggested should be first processed in another Tech mod, using ore dictionary and CraftTweaker where needed. Even if you don't want to add tech mods, with just CT you can add any form of recipe transformation, ie: `Bloomery`
