### ISSUE TITLE
Osmium smelt into unknown metal

### ISSUE THREAD

**Issue by aliceingame** [TFC-Metallum/TFC-Metallum#34]
Smelted small osmium in a vessel, resulted in unknown metal.

JEI say it would melt into osmium, that is wrong.
Did not test in TNG, but in Classic, melting a wrong alloy recipe or trying to smelt an invalid ore would just do nothing and ore would stay in vessel.

**Comment by Mrthomas20121** [comment]
I believe Osmium isn't supposed to melt. It's added for compatibility with other mods(like aluminium and titanium).

**Comment by aliceingame** [comment]
If the decision is to make it turn into unknown because it is not the right processing method, I can accept it, but at least JEI should not sow it as a valid processing method.

**Comment by aliceingame** [comment]
I think that I figured it out, the ore that should not melt, like osmium, should have their "can melt" set to false
ItemRegistry.registerItemMetal(IIngredient input, String metal, int units, bool canMelt)

This would turn the ore to something similar to TFC iron ore, that cannot be melted directly into metal, but require specific processing. For osmium and aluminium, yes you can let that to other mods or scrips, no problem. But making it melt into unknown metal in strange.

There is also an issue with the melt temperature of osmium, because the melting temperature is too high. Making it impossible for mod/scripts author to make anything that  would require melting osmium. For example if I want to create an osmium alloy, it's not possible as refined osmium items (ingot) do not melt.

**Comment by DisasterMoo** [comment]
Sorry for late response, and yes, osmium isn't supposed to be melted anywhere with just Metallum and TFC. I will take a look how feasible is to actually make JEI show that it's gonna melt to unknown alloy or even if it is possible to not melt at all and stay in the small vessel.
