### ISSUE TITLE
About Chinese Translated

### ISSUE THREAD

**Issue by 9N9N7S** [TFC-Metallum/TFC-Metallum#35]
Hello. I very like TFC-Metallum. So I have finished the translation your mod into Chinese. I hope to add Chinese in the next version. I will continue to follow up the translation. But I don't known how to send the translation for you. Help me please. English is not my mother language. I'm not good at English.

**Comment by DisasterMoo** [comment]
I suggest then that you check tutorials about how to work with github. What you should learn is how to fork a repository, make changes and commit then before you can open a pull request.

**Comment by 9N9N7S** [comment]
Ok. I get it.
