### ISSUE TITLE
Missing lang entries

### ISSUE THREAD

**Issue by Mrthomas20121** [TFC-Metallum/TFC-Metallum#40]
Mithril and Nickel Silver have no lang entries for the molds.
![image](https://user-images.githubusercontent.com/34064092/82732618-8b46d700-9d0e-11ea-9de4-631d7631d384.png)
they have a lang entry for the ingot mold but not for the others mold(tfc tech mold not included as they have a lang entry).

**Comment by Gargarien** [comment]
> Mithril and Nickel Silver have no lang entries for the molds.
> ![image](https://user-images.githubusercontent.com/34064092/82732618-8b46d700-9d0e-11ea-9de4-631d7631d384.png)
> they have a lang entry for the ingot mold but not for the others mold(tfc tech mold not included as they have a lang entry).

and...all lamp ._.
![image](https://user-images.githubusercontent.com/58866716/82768352-35ba1980-9e37-11ea-9b4a-a0960132e164.png)

**Comment by Mrthomas20121** [comment]
i fixed that with my upcoming pr. this can be closed now.
