### ISSUE TITLE
Add "Aluminum" to Aluminium's oreDictionary

### ISSUE THREAD

**Issue by M8-u** [TFC-Metallum/TFC-Metallum#42]
Immersive engineering requires Aluminum (alumin-um) when Metallum adds Aluminium (alumin-ium). For this reason, Metallum aluminium cannot be used to craft immersive engineering "aluminum" recipes.
Screenshots:
![Screen Shot 2020-05-26 at 12 12 22 PM](https://user-images.githubusercontent.com/53875064/82924547-7bb3d200-9f4a-11ea-958a-5f659e6a1628.png)
![Screen Shot 2020-05-26 at 12 12 29 PM](https://user-images.githubusercontent.com/53875064/82924553-7ce4ff00-9f4a-11ea-8b63-f78df88f73a6.png)
Metallum version: 1.2.6

**Comment by Gargarien** [comment]
AHAHAHAA THIS IS EXACTLY WHAT I'VE BEEN STRUGGLING WITH ALL WEEK
dude, both options are unfortunately correct, I came to the following solution: download crafttweaker and create a file with the .ZS extension in the scripts folder
here is a script you need to enter, I have everything working
`var ores = ["plate", "sheet", "stick", "screw", "bolt", "rackwheel", "nugget", "wire", "gear", "ingot", "dust", "rod"] as string[];
for ore in ores {
  var aluminumOre = oreDict[ore+"Aluminum"];
  aluminumOre.addAll(oreDict[ore+"Aluminium"]);
}`
