### ISSUE TITLE
TFC Guide Book Via Patchouli

### ISSUE THREAD

**Issue by Mathias-Ademar** [TFC-Metallum/TFC-Metallum#47]
should be noted that the borax quern recipes (and possibly others, but this one is the one that got me) is being pinged my the guide book, but causes a crash when it does. AnoddeCathode said it was cause Metallium removed or edited the quern stuff, and so is the source of the crash (he noticed the removed recipes when he was poking around the metallium code). 

crash report linked below
[crash-2020-08-17_15.24.20-client.txt](https://github.com/TFC-Metallum/TFC-Metallum/files/5086652/crash-2020-08-17_15.24.20-client.txt)

**Comment by cole4114** [comment]
I am having the same issue
[crash-2020-08-26_18.06.40-client.txt](https://github.com/TFC-Metallum/TFC-Metallum/files/5133115/crash-2020-08-26_18.06.40-client.txt)

**Comment by DisasterMoo** [comment]
Fixed by https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/e91ca52d35eb73de59bcc13511deb55e8a34554d
