### ISSUE TITLE
The melting point of the alloy should not be higher than 1601℃

### ISSUE THREAD

**Issue by HazelnutCat** [TFC-Metallum/TFC-Metallum#50]
If the melting point of the alloy is higher than 1601℃, the crucible will not be able to export the alloy.

**Comment by DisasterMoo** [comment]
That's intended, metallum's purpose is to be a bridge between TFC and other mods, so if you want to melt said materials i recommend adding [TFCTech](https://www.curseforge.com/minecraft/mc-mods/tfctech-unofficial) or another mod that process those metals.
