### ISSUE TITLE
Suggestion: Add option to globally disable metals

### ISSUE THREAD

**Issue by InkyMiner** [TFC-Metallum/TFC-Metallum#51]
Currently I see no built-in option to disable metals and their items. If I don't want to use some metals I, I would have to disable all recipes and hide all items of those unwanted metals using crafttweaker, right? (in my case thousands)
It would be easier for pack makers if there was a global config. Something like 
"B:'Enable all items and recipes using cobalt'=true"
"B:'Enable all items and recipes using osmium'=false"
or similar.

Thank you for your work on this mod so far!

**Comment by DisasterMoo** [comment]
Added in #53
