### ISSUE TITLE
I really like the way the ingots are placed on the ground in this Mod!!!

### ISSUE THREAD

**Issue by Emperorsking** [TFC-Metallum/TFC-Metallum#54]
This Mod places metal ingots on the ground, which makes me feel very immersive while playing, but I have to install TFC every time I want to use this feature. Most of the time, I don't want to play TFC survival mode, I wish I could separate this feature out and make it a Mod, any suggestions? What should I do?

**Comment by ACGaming** [comment]
There's [Stackable](https://www.curseforge.com/minecraft/mc-mods/stackable) and [Charset Immersion](https://www.curseforge.com/minecraft/mc-mods/charset-immersion).

**Comment by Emperorsking** [comment]
Sorry?can you be more specific?

**Comment by Emperorsking** [comment]
Thank you very much for your answer! How helpful! I've solved the problem! Thank you so much!!!

**Comment by DisasterMoo** [comment]
Sorry for the late reply, just gonna add a comment:

That feature is actually from TFC itself, this addon is mostly for adding other mods' metals to TFC, so it can have those little things and also be integrated with TFC systems (like melting, alloying and other things).
